/**
 * The published documentation, and the link resolution that makes it navigable.
 *
 * Content comes from `docs-content.json`, generated by `scripts/build-docs.mjs`
 * from `docs/` — see that file for why it is generated rather than read.
 *
 * The interesting part here is `linkFor`. These documents cross-reference each
 * other by relative path, and they were written for people reading the
 * repository, where every link resolves. On a published subset most of them
 * still do, some point at documents deliberately not published, and a section
 * whose internal links 404 is worse than one with no links at all. So a link is
 * resolved against the *published* set: what maps becomes a route, and what does
 * not becomes plain text rather than a promise the page cannot keep.
 */

import content from "./docs-content.ts";

export type Doc = {
  file: string;
  slug: string;
  title: string;
  group: string;
  body: string;
};

export const DOCS: Doc[] = content.docs;

export const BY_SLUG = new Map(DOCS.map((d) => [d.slug, d]));

/** The published docs in reading order, grouped as the index presents them. */
export function groups(): { group: string; docs: Doc[] }[] {
  const out: { group: string; docs: Doc[] }[] = [];
  for (const doc of DOCS) {
    const last = out[out.length - 1];
    if (last && last.group === doc.group) last.docs.push(doc);
    else out.push({ group: doc.group, docs: [doc] });
  }
  return out;
}

/** `docs/ingestion/write-api.md` + `../graph.md` → `graph.md`. */
function resolve(fromFile: string, href: string): string {
  const base = fromFile.split("/").slice(0, -1);
  const parts = href.split("/");
  const stack = [...base];
  for (const part of parts) {
    if (part === "." || part === "") continue;
    if (part === "..") stack.pop();
    else stack.push(part);
  }
  return stack.join("/");
}

/**
 * What a link inside `doc` should point at, or null to drop it.
 *
 * Anchors and absolute URLs pass through. A relative `.md` path resolves
 * against the published set. Anything else — an image, a path into `api/`,
 * a document not published — returns null.
 */
export function linkFor(doc: Doc, href: string): string | null {
  if (!href) return null;
  if (href.startsWith("#")) return href;
  if (/^(https?:|mailto:)/.test(href)) return href;

  const [pathPart, anchor] = href.split("#");
  if (!/\.md$/i.test(pathPart)) return null;

  const target = resolve(doc.file, pathPart);
  const found = DOCS.find((d) => d.file === target);
  if (!found) return null;
  const suffix = anchor ? `#${anchor}` : "";
  return found.slug ? `/docs/${found.slug}${suffix}` : `/docs${suffix}`;
}

/** Every link in the published set that cannot be resolved, for the check. */
export function unresolved(): { from: string; href: string }[] {
  const broken: { from: string; href: string }[] = [];
  for (const doc of DOCS) {
    for (const match of doc.body.matchAll(/\[[^\]]*\]\(([^)\s]+)\)/g)) {
      const href = match[1];
      if (href.startsWith("#") || /^(https?:|mailto:)/.test(href)) continue;
      if (!/\.md$/i.test(href)) continue;
      if (linkFor(doc, href) === null) broken.push({ from: doc.file, href });
    }
  }
  return broken;
}
